#include subscripts/common/cards.ahk
#include subscripts/common/diacritics.ahk
#include subscripts/common/ipa.ahk
#include subscripts/common/letters.ahk
#include subscripts/common/logic.ahk
#include subscripts/common/math.ahk
#include subscripts/common/music.ahk
#include subscripts/common/other.ahk
#include subscripts/common/subscripts.ahk
#include subscripts/common/superscripts.ahk
#include subscripts/common/typography.ahk